# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stockstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stockstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stockstream.proto\x12\x0bstockstream\"#\n\x10SubscribeRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"D\n\x10StockPriceUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32g\n\x11StockDataStreamer\x12R\n\x10SubscribeSymbols\x12\x1d.stockstream.SubscribeRequest\x1a\x1d.stockstream.StockPriceUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stockstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=34
  _globals['_SUBSCRIBEREQUEST']._serialized_end=69
  _globals['_STOCKPRICEUPDATE']._serialized_start=71
  _globals['_STOCKPRICEUPDATE']._serialized_end=139
  _globals['_STOCKDATASTREAMER']._serialized_start=141
  _globals['_STOCKDATASTREAMER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
